# NUMPY

Importamos la librería numpy (si no funciona realizar __pip install numpy__ desde una consola de comandos)

In [1]:
import numpy

In [2]:
# Creamos nuestro primer array

arr = numpy.array([10, 20, 98, 34])

arr

array([10, 20, 98, 34])

In [3]:
# Observamos el tipo de clase que tiene un array
print(type(arr))

<class 'numpy.ndarray'>


Algo muy extendido entre la comunidad de desarrolladores de Python es utilizar __alias__ en las librerías, para acortar su nombre e identificarlas más fácilmente, en el caso de __numpy__ utilizaremos el alias __np__

In [4]:
import numpy as np

# Creamos de nuevo un array
arr = np.array([23, 42, 58])

arr

array([23, 42, 58])

Tupla como array

In [5]:
mi_tupla = (1, 58, 63, 45)
print(type(mi_tupla))

arr_tuple = np.array(mi_tupla)

print(arr_tuple)
print(type(arr_tuple))

<class 'tuple'>
[ 1 58 63 45]
<class 'numpy.ndarray'>


Diccionario como array

In [6]:
my_dict = {'one': 'uno', 
           'two': 'dos',
           'three': 'tres'}

dict_list = list(my_dict.items())
print(dict_list)

arr_dict = np.array(dict_list)
print(arr_dict)

[('one', 'uno'), ('two', 'dos'), ('three', 'tres')]
[['one' 'uno']
 ['two' 'dos']
 ['three' 'tres']]


### Dimensiones de un array

Verficamos las dimensiones de un array con la función <code>__ndim__</code>

In [7]:
a = np.array(42)

In [8]:
b = np.array([1, 2, 3, 4, 5])

In [9]:
c = np.array([
    [1, 2, 3], [4, 5, 6]
])

In [10]:
d = np.array([
    [
        [1, 2, 3], [4, 5, 6]
    ], 
    [
        [1, 2, 3], [4, 5, 6]
    ]
])

In [11]:
e = np.array([
    [
        [[1, 2, 3], [4, 5, 6]], 
        [[1, 2, 3], [4, 5, 6]],
        [[1, 2, 3], [4, 5, 6]], 
        [[1, 2, 3], [4, 5, 6]]
    ]
])

In [12]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
4


### Seleccionando elementos de un array



In [13]:
b[0]

1

In [14]:
c[0]

array([1, 2, 3])

In [15]:
c[0][2]

3

In [16]:
d[1]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
d[1][0]

array([1, 2, 3])

In [18]:
d[1][0][2]

3

## Estructura de un array

Para ello utilizamos la función <code>__shape__</code> que nos devuelve la siguiente información
* (__longitud elementos dim 1__, __longitud elementos dim 2__,..., __longitud elementos dim n__)

In [19]:
print(a.shape) # No tiene dimensiones, solamente es el número 42

()


In [20]:
print(b.shape) # Longitud 5 dimensión 1

(5,)


In [21]:
print(c.shape) # Longitud 2, cada lista tiene 3 elemento

(2, 3)


In [22]:
print(d.shape) # Longitud 2, cada sub-lista tiene 2 listas, de 3 elementos

(2, 2, 3)


In [23]:
print(e.shape) # Longitud 1, 
               # dentro de esta lista hay 4 sub-listas, 
               # cada sub-lista tiene 2 listas, 
               # de 3 elementos

(1, 4, 2, 3)


## Indexando arrays y creando _slices_ de arrays de una dimensión

In [24]:
my_array = np.arange(11)

In [25]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

De posición 0 a 3

In [26]:
my_array[0:3] # De posición 0 a 3

array([0, 1, 2])

De posición 2 a 7

In [27]:
my_array[2:7] # De posición 2 a 7

array([2, 3, 4, 5, 6])

De inicio a 6

In [28]:
my_array[:6] # De inicio a 6

array([0, 1, 2, 3, 4, 5])

De 6 a final

In [29]:
my_array[6:] # De 6 a final

array([ 6,  7,  8,  9, 10])

De inicio a 9 de tres en tres elementos

In [30]:
my_array[:9:3] # De inicio a 9 de tres en tres elementos

array([0, 3, 6])

De 6 a fin de dos en dos elementos

In [31]:
my_array[6::2] # De 6 a fin de dos en dos elementos

array([ 6,  8, 10])

Posición 2 empezando por el final

In [32]:
my_array[-2] # Posición 2 empezando por el final

9

De inicio hasta el elemento -3 del array

In [33]:
my_array[:-3] # De inicio hasta el elemento -3 del array

array([0, 1, 2, 3, 4, 5, 6, 7])

Array reverso

In [34]:
my_array[::-1] # Array reverso

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

De fin (reverso) a inicio tomados de 2 en 2

In [35]:
my_array[::-2] # De fin (reverso) a inicio tomados de 2 en 2

array([10,  8,  6,  4,  2,  0])

## Manipulando dimensiones de un array

Podemos definir las dimensiones de un array con la función <code>__reshape__</code>, por ejemplo, crear un array de 2 listas, con 3 sublistas de 6 elementos cada una.

In [36]:
new_array = np.arange(36).reshape(2,3,6)

In [37]:
new_array

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

Algo más sencillo

In [38]:
basic_array = np.arange(3).reshape(1,3)
basic_array

array([[0, 1, 2]])

Podemos recodificar otros arrays a una nueva dimensión

In [39]:
new_dims = e.reshape(2,2,6)
new_dims

array([[[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]],

       [[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]]])

Lo contrario de reshape, es la función <code>__ravel__</code> y <code>__flatten__</code>, es decir, eliminar todas las dimensiones y dejar un array plano

In [40]:
new_dims.ravel()

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4,
       5, 6])

In [41]:
new_dims.flatten()

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4,
       5, 6])

La principal diferencia entre los dos es que __flaten__ devuelve una copia y __ravel__ devuelve una vista, es decir, si hacemos un cambio en el array original, se verá reflejado en la variable asignada a ravel.

Es importante recordar que los arrays son mutables, es decir, si no realizamos una copia correctamente, los dos arrays compartirán las mismas posiciones de memoria.

## _Stacking_ (apliando) de arrays

Los arrays pueden ser apilados ( _stacking_ ) de forma horizontal, vertical o en profundad. Veamos algunos casos y las funciones necesarias para ello.

In [42]:
pares = np.array([
    [0, 2, 4],
    [6, 8, 10],
    [12, 14, 16]
])

impares = np.array([
    [1, 3, 5],
    [7, 9, 11],
    [13, 15, 17]
])

* **Stacking Horizontal** <code>__hstack__</code>

In [43]:
np.hstack((pares, impares)) # Apila los arrays en referencia a la la longitud 3

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

* **Stacking Vertical** <code>__vstack__</code>

In [44]:
np.vstack((pares, impares)) # Apila los arrays en referencia al número de elementos.

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

* Ambas funciones son equivalentes a <code>__concatenate__</code>, en este caso el elemento que diferencia el método de unión es el parámetro axis. 0 por filas, 1 columnas

In [45]:
np.concatenate((pares, impares), axis=1)

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

In [46]:
np.concatenate((pares, impares), axis=0)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Con <code>**dstack**</code> podemos apilar los arrays de elemento a elemento (primero con primero, segundo con segundo ...)

In [47]:
np.dstack((pares, impares))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

## Splitting (dividiendo) arrays

Al igual que podemos apilar o unir arrays, también podemos dividir arrays en nuevos arrays, los criterios de unión son muy similares a los de división: Horizaontal, vertical y en profundidad 

* Para división horizontal <code>**hsplit**</code>, importante, esta función toma un valor de división que debe ser igual al número de elementos del array (por lista)

In [48]:
np.hsplit(pares, 3)

[array([[ 0],
        [ 6],
        [12]]),
 array([[ 2],
        [ 8],
        [14]]),
 array([[ 4],
        [10],
        [16]])]

* Para división vertical <code>**vsplit**</code>, importante, esta función toma un valor de división que debe ser igual al número de elementos del array (por lista)

In [49]:
np.vsplit(pares, 3)

[array([[0, 2, 4]]), array([[ 6,  8, 10]]), array([[12, 14, 16]])]

* Equivalentemente tenemos la función <code>**split**</code> que nos permite realizar la división del array por columnas o filas

In [50]:
np.split(pares, 3, axis=1)

[array([[ 0],
        [ 6],
        [12]]),
 array([[ 2],
        [ 8],
        [14]]),
 array([[ 4],
        [10],
        [16]])]

In [51]:
np.split(pares, 3, axis=0)

[array([[0, 2, 4]]), array([[ 6,  8, 10]]), array([[12, 14, 16]])]

Finalmente, con <code>**dsplit**</code> podemos realizar la división por profundidad. Importante: Este tipo de división, requiere arrays de dimensión 3 como mínimo.

In [52]:
big = np.arange(27).reshape(3, 3, 3)

In [53]:
big

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [54]:
np.dsplit(big, 3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]),
 array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]),
 array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

## Atributos de un array

* <code>**ndim**</code> Muestra el número de dimensiones de un array

In [55]:
big.ndim

3

* <code>**size**</code> Cuenta el número de elementos.

In [56]:
big.size

27

* <code>**itemsize**</code> Espacio que ocupa en bytes cada elemento del array

In [57]:
big.itemsize

4

* <code>**nbytes**</code> Tamaño de todo el array en bytes

In [58]:
big.nbytes

108

* <code>**T**</code> Transpuesta del array

In [59]:
big.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

## Convirtiendo arrays

Es posible extraer slices del array o, simplemente todo el array para obtener listas o modificar el tipo del array, en este caso utilizaremos dos funciones para realizar conversiones sobre el array.

* <code>**tolist**</code> Convierte a lista el array o un slice del mismo

In [60]:
lista = big.tolist()

In [61]:
print(lista)
print(type(lista))

[[[0, 1, 2], [3, 4, 5], [6, 7, 8]], [[9, 10, 11], [12, 13, 14], [15, 16, 17]], [[18, 19, 20], [21, 22, 23], [24, 25, 26]]]
<class 'list'>


* <code>**astype**</code> Para modificar el tipo del array.

In [62]:
big.astype(float)

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]]])

In [63]:
big.astype(str)

array([[['0', '1', '2'],
        ['3', '4', '5'],
        ['6', '7', '8']],

       [['9', '10', '11'],
        ['12', '13', '14'],
        ['15', '16', '17']],

       [['18', '19', '20'],
        ['21', '22', '23'],
        ['24', '25', '26']]], dtype='<U11')

In [64]:
big.astype(int)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

## Copias y Vistas de un array.

Es importante mencionar que al igual que las listas los arrays comparten posiciones en nuestra memoria física, por lo tanto, si no utilizamos los comandos necesario para realizar una copia de un array correctamente, los cambios que hagamos en el array_a, se verán reflejados en el array_b.

Vamos a ver el ejemplo más básico, hacer una copia de un array asignándolo a una nueva variable.

In [65]:
# Definimos un array con elementos del 2 hasta 20
arr = np.arange(2, 20)

In [66]:
# Asignamos las dos últimas posiciones a la variable b
b = arr[-2:]
b

array([18, 19])

In [67]:
# Asignamos todas las posiciones del array b a cero.
b[::] = 0
b

array([0, 0])

In [68]:
# Los cambios se reflejan en nuestra variable arr
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,  0,
        0])

Vamos a ver ahora otro ejemplo similar, obtendremos las primeras cinco posiciones del array, se las asignaremos a otra variable, les daremos valor 100 y veremos que estos cambios se ven reflejados en nuestro array original

In [69]:
array_dos = np.arange(0, 31)

In [70]:
c = array_dos[0:5]

In [71]:
c[::] = 100
c

array([100, 100, 100, 100, 100])

In [72]:
array_dos

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30])

En los dos ejemplos anteriores vemos que los arrays hay sufrido cambios producidos en los arrays copia, algo similar sucede si utilizamos la función <code>**view**</code>, su uso se aconseja para mostrar arrays, pero no para realizar cambios sobre los mismos.

In [73]:
array_1 = np.array([[10,10], [2,3], [4,5]]) 
array_1

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

Creamos un segundo array basado en el primero

In [74]:
array_dos = array_1.view()

array_dos

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

Con el comando <code>__id()__</code> vemos que las posiciones son iguales

In [75]:
id(array_1)

2259373835968

In [76]:
id(array_dos)

2259374351104

Modificamos el segundo array

In [77]:
array_dos[0] = [10000, 3]

array_dos

array([[10000,     3],
       [    2,     3],
       [    4,     5]])

Comprobamos que ha ocurrido lo mismo en el primero

In [78]:
array_1

array([[10000,     3],
       [    2,     3],
       [    4,     5]])

Para evitar que esto ocurra, si realmente queremos obtener una copia de un array para su posterior procesamiento o modificación, lo mejor es copiar el array con el comando <code>__copy()__</code>

In [79]:
array_copiado = array_1.copy()

Comprobamos posiciones de memoria

In [80]:
print(id(array_1))
print(id(array_copiado))

2259373835968
2259374322192


Realizamos una modificación en el array original

In [81]:
array_1[1] = [2200, 34]

array_1

array([[10000,     3],
       [ 2200,    34],
       [    4,     5]])

Vemos si los cambios aparecen en nuestra copia

In [82]:
array_copiado

array([[10000,     3],
       [    2,     3],
       [    4,     5]])

## Operaciones sobre arrays

Existen varias operaciones que podemos realizar sobre arrays, es importante enfatizar en la importancia de saber sobre qué eje ( *axis* ) de los arrays queremos realizar la suma

* Suma <code>**sum**</code>

In [83]:
e = np.array([[[1, 0], [0, 0]],
              [[1, 1], [1, 0]],
              [[1, 0], [0, 1]]]
            )

e.sum(axis = 0)

array([[3, 1],
       [1, 1]])

El resultado significa que sumando las columnas del primer componente que es:
[1. 0]
[1, 1]
[1, 0]

Obtenemos que las filas en la columna suman 3 y en la segunda columna 1, por lo tanto [3, 1]

En el segundo componente que es:
[0, 0]
[1, 0]
[0, 1]

Obtenemos que las filas de la primera columna suman 1 y de la segunda 1 también, por lo tanto [1, 1]

In [84]:
e.sum(axis=1)

array([[1, 0],
       [2, 1],
       [1, 1]])

En este caso cada dimensión, funciona a nivel de fila, por lo tanto, si sumamos la primera fila que sería [1 + 0], [0 + 0] = [1, 0]

La segunda fila: [1 + 1], [1 + 0] = [2, 1]

La tercera: [1 + 0], [0 + 1] = [1, 1]

* <code>**empty**</code> genera un array con valores arbitrarios

In [85]:
nothing = np.empty(10)
nothing

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.60218491e-306,
       1.89146896e-307, 7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
       1.29061142e-306, 5.53353523e-322])

* <code>**ones**</code> genera un array solamente con unos.

In [86]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

* <code>**zeros**</code> genera un array solamente con ceros.

In [87]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

* <code>**random**</code> Como función. Importa una serie de funciones para generación de números aleatorios de diferente distribución. Algunos de los diferentes valores que podemos generar son:

* <code>**rand**</code>: Valores aleatorios.
* <code>**randn**</code> : Valores aleatorios siguiendo una distribución normal.
* <code>**randint**</code>: Valores aleatorios enteros desde menor valor a mayor.
* <code>**random**</code>: Valores aleatorios de tipo float entre el intervalo [0.0, 1.0].
* <code>**beta**</code>: Valores que siguen una distribución Beta.
* <code>**binomial**</code>: Valores aleatorios que siguen una distribución Binomial.
* <code>**gamma**</code>: Valores que siguen una distribución Gamma.

Todos los diferentes valores aleatorios y distribuciones que podemos realizar se encuentran en el siguiente link. https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html

In [88]:
rand = np.random.rand(10)
rand

array([0.40276909, 0.53909085, 0.21001948, 0.43101847, 0.85290298,
       0.29267191, 0.23259428, 0.45543234, 0.32661333, 0.14364282])

In [89]:
randn = np.random.randn(10)
randn

array([-0.45122686, -0.54382636, -2.20458819,  1.52234174, -2.18575025,
       -0.59545547, -0.05458969, -1.44117766,  0.07652807,  0.10681569])

In [90]:
randint = np.random.randint(20, 100, 10)
randint

array([83, 32, 84, 32, 67, 41, 40, 28, 52, 65])

In [91]:
random = np.random.random(10)
random

array([0.37282558, 0.41383953, 0.68760449, 0.99051508, 0.54018014,
       0.99090244, 0.95581069, 0.35652923, 0.03318906, 0.25203896])

In [92]:
beta = np.random.beta(0.2, 0.5, 10)
beta

array([9.94504963e-01, 2.10532611e-03, 7.70362871e-04, 4.10990216e-03,
       9.78075674e-01, 8.39217215e-05, 1.26078931e-01, 9.75163603e-01,
       1.50341102e-04, 7.14771250e-01])

In [93]:
binomial = np.random.binomial(10, 0.5, 10)
binomial

array([2, 6, 6, 7, 4, 5, 6, 7, 6, 7])

In [94]:
gamma = np.random.gamma(0.25, 0.3, 10)
gamma

array([8.96687949e-03, 1.30704991e-06, 1.15881212e-01, 1.17297221e-01,
       2.75035760e-01, 4.30492608e-02, 5.95367713e-02, 1.53402195e+00,
       1.22249166e-07, 2.29339631e-03])

* <code>**round**</code>: Permite redondear a n decimales todo un array.

In [95]:
gamma.round(2)

array([0.01, 0.  , 0.12, 0.12, 0.28, 0.04, 0.06, 1.53, 0.  , 0.  ])

* <code>**fill**</code>: Permite rellenar un array con un valor pasado por parámetro.

In [96]:
zero_array = np.zeros(20)
zero_array[5:15].fill(5)
zero_array

array([0., 0., 0., 0., 0., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 0., 0.,
       0., 0., 0.])

* <code>**mean**</code>: Realiza la media del array o por uno de sus ejes.

In [97]:
e.mean(axis = 0)

array([[1.        , 0.33333333],
       [0.33333333, 0.33333333]])

In [98]:
e.mean(axis = 1)

array([[0.5, 0. ],
       [1. , 0.5],
       [0.5, 0.5]])

In [99]:
e.mean()

0.5

* <code>**dot**</code>: Producto de matrices

In [100]:
e.dot(gamma) # Tenemos que asegurarnos de que son de la misma dimensión.

ValueError: shapes (3,2,2) and (10,) not aligned: 2 (dim 2) != 10 (dim 0)

In [ ]:
e.dot(d)

* <code>**min**</code>: Valor mínimo del array o de uno de sus ejes

In [ ]:
aux = np.array([
    [1, 100, 5],
    [2, 4, 0]
])

aux.min()

In [ ]:
aux.min(axis=0)

In [ ]:
aux.min(axis=1)

* <code>**max**</code>: Valor máximo del array o de uno de sus ejes

In [ ]:
print(aux.max())
print(aux.max(axis=0))
print(aux.max(axis=1))

* <code>**argmin**</code>: Posición del índice con el valor mínimo de un array

In [ ]:
aux.argmin()

* <code>**argmax**</code>: Posición del índice con el valor máximo de un array

In [ ]:
aux.argmax()

* <code>**sort**</code>: Ordenar elementos de un array.

In [ ]:
aux.sort()
aux